# # -*- coding: utf-8 -*-
# """app.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/12CutWo04XNJMj5et41yenpXPPSRlDQJZ
# """

# from flask import Flask, render_template_string, request

# app = Flask(__name__)

# # --- Inventario ---
# inventario = {
#     "camisa": {"precio": 50000, "descuento": 10},
#     "pantalon": {"precio": 80000, "descuento": 0},
#     "zapatos": {"precio": 120000, "descuento": 20},
# }

# def consultar_producto(nombre_producto):
#     nombre_producto = nombre_producto.lower()
#     if nombre_producto in inventario:
#         producto = inventario[nombre_producto]
#         precio = producto["precio"]
#         descuento = producto["descuento"]
#         if descuento > 0:
#             precio_final = precio - (precio * descuento / 100)
#             return f"✅ '{nombre_producto}' cuesta {precio} pesos, con {descuento}% de descuento. Precio final: {precio_final} pesos."
#         else:
#             return f"✅ '{nombre_producto}' cuesta {precio} pesos y no tiene descuento."
#     else:
#         return f"❌ '{nombre_producto}' no está en el inventario."

# # --- Plantilla HTML ---
# html = """
# <!DOCTYPE html>
# <html lang="es">
# <head>
#     <meta charset="UTF-8">
#     <title>ChatBot Inventario</title>
#     <style>
#         body { font-family: Arial; background: #f4f6f9; display:flex; justify-content:center; align-items:center; height:100vh;}
#         .chatbox { background:white; padding:20px; border-radius:12px; box-shadow:0 4px 10px rgba(0,0,0,0.1); width:400px;}
#         input, button { padding:10px; width:100%; margin-top:10px; border-radius:8px; border:1px solid #ccc;}
#         button { background:#007BFF; color:white; border:none; cursor:pointer;}
#         button:hover { background:#0056b3;}
#         .respuesta { margin-top:15px; padding:10px; background:#eaf4ff; border-radius:8px;}
#     </style>
# </head>
# <body>
#     <div class="chatbox">
#         <h2>🤖 ChatBot Inventario</h2>
#         <form method="POST">
#             <input type="text" name="producto" placeholder="Ej: camisa" required>
#             <button type="submit">Consultar</button>
#         </form>
#         {% if respuesta %}
#         <div class="respuesta">{{ respuesta }}</div>
#         {% endif %}
#     </div>
# </body>
# </html>
# """

# @app.route("/", methods=["GET", "POST"])
# def home():
#     respuesta = ""
#     if request.method == "POST":
#         producto = request.form["producto"]
#         respuesta = consultar_producto(producto)
#     return render_template_string(html, respuesta=respuesta)

# if __name__ == "__main__":
#     app.run(host="0.0.0.0", port=5000)

from flask import Flask, render_template_string, request
import os

app = Flask(__name__)

# ---------------- INVENTARIO ----------------
inventario = {
    "camisa": {"precio": 50000, "descuento": 10},
    "pantalon": {"precio": 80000, "descuento": 0},
    "zapatos": {"precio": 120000, "descuento": 20},
}

def consultar_producto(nombre_producto):
    nombre_producto = nombre_producto.lower()
    if nombre_producto in inventario:
        producto = inventario[nombre_producto]
        precio = producto["precio"]
        descuento = producto["descuento"]
        if descuento > 0:
            precio_final = precio - (precio * descuento / 100)
            return f"✅ '{nombre_producto}' cuesta {precio} pesos, con {descuento}% de descuento. Precio final: {precio_final:.0f} pesos."
        else:
            return f"✅ '{nombre_producto}' cuesta {precio} pesos y no tiene descuento."
    else:
        return f"❌ '{nombre_producto}' no está en el inventario."

# ---------------- HTML ----------------
html = """
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>ChatBot Inventario</title>
    <style>
        body {
            font-family: Arial;
            background: #f4f6f9;
            display:flex;
            justify-content:center;
            align-items:center;
            height:100vh;
        }
        .chatbox {
            background:white;
            padding:20px;
            border-radius:12px;
            box-shadow:0 4px 10px rgba(0,0,0,0.1);
            width:400px;
        }
        input, button {
            padding:10px;
            width:100%;
            margin-top:10px;
            border-radius:8px;
            border:1px solid #ccc;
        }
        button {
            background:#007BFF;
            color:white;
            border:none;
            cursor:pointer;
        }
        button:hover {
            background:#0056b3;
        }
        .respuesta {
            margin-top:15px;
            padding:10px;
            background:#eaf4ff;
            border-radius:8px;
        }
    </style>
</head>
<body>
    <div class="chatbox">
        <h2>🤖 ChatBot Inventario</h2>
        <form method="POST">
            <input type="text" name="producto" placeholder="Ej: camisa" required>
            <button type="submit">Consultar</button>
        </form>

        {% if respuesta %}
        <div class="respuesta">{{ respuesta }}</div>
        {% endif %}
    </div>
</body>
</html>
"""

# ---------------- RUTA ----------------
@app.route("/", methods=["GET", "POST"])
def home():
    respuesta = ""
    if request.method == "POST":
        producto = request.form["producto"]
        respuesta = consultar_producto(producto)
    return render_template_string(html, respuesta=respuesta)

# ---------------- ARRANQUE ----------------
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
